#! /usr/bin/bash

find AutoSphinx -name "flycheck*.py" -exec rm {} \;
find AutoSphinx -name "parsetab.py" -exec rm {} \;

api=doc/sphinx/source/api

echo
echo Generate RST API files
./bin/generate-rst-api AutoSphinx

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html #--clean
popd
