#! /usr/bin/bash

find Pyterate -name "flycheck*.py" -exec rm {} \;
find Pyterate -name "parsetab.py" -exec rm {} \;

api=doc/sphinx/source/api
rm -rf ${api}

echo
echo Generate RST API files
./bin/pyterate-rst-api Pyterate

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html #--clean
popd
