#! /usr/bin/bash

# Regenerate from scratch
examples=doc/sphinx/source/examples
rm -rf ${examples}

echo
echo Generate RST examples files
# ./bin/pyterate --skip-external-figure --skip-figure
./bin/pyterate # --force

# exit 0

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html # --clean
popd
